spring:
  datasource:
    url: jdbc:postgresql://jobly-jobs.c3q4ia2gg831.eu-west-1.rds.amazonaws.com:5432/
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}